import fs from "node:fs/promises";

export interface PdfExtraction {
  title?: string;
  authors: string[];
  language?: string;
  publisher?: string;
  publishedAt?: Date;
  pageCount: number;
  cover?: { buffer: Buffer; ext: string };
}

// PDF metadata extraction via pdfjs-dist.
//
// v1 deliberately does not render a cover image — that would need a canvas
// implementation in Node (node-canvas / @napi-rs/canvas), and the heavy
// native deps don't pull their weight before the UI is even sketched. PDF
// covers can be added in a later phase; until then, the UI falls back to a
// placeholder for the PDF format badge.
export async function extractPdf(filePath: string): Promise<PdfExtraction> {
  // pdfjs-dist v5 references DOM globals (DOMMatrix/ImageData/Path2D) that Node
  // does not provide — even the legacy build throws "DOMMatrix is not defined"
  // without them. Register them once from @napi-rs/canvas (a dependency, also
  // used for cover rendering) before pdfjs loads.
  await ensurePdfGlobals();
  // pdfjs-dist v5 ships ESM; the legacy build is more forgiving on Node
  // runtimes that haven't gotten newer Web APIs.
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs");

  // Read the file ONCE; both the metadata parser and the cover renderer work
  // off these bytes instead of each re-opening the path (ROBUST-04 — avoids a
  // second whole-file read + the RSS spike of holding two copies serially).
  const buffer = await fs.readFile(filePath);
  // pdfjs takes ownership of (and may neuter) the buffer it receives, so give
  // it a fresh Uint8Array view here and hand the cover renderer a SEPARATE
  // copy below — sharing one view would corrupt whichever runs second.
  const data = new Uint8Array(buffer);

  const loadingTask = pdfjs.getDocument({
    data,
    disableFontFace: true,
    useWorkerFetch: false,
    useSystemFonts: false,
  });

  const doc = await loadingTask.promise;
  try {
    const md = await doc.getMetadata().catch(() => null);
    const info = (md?.info ?? {}) as Record<string, unknown>;
    const xmp = md?.metadata ?? null;

    // Info dict is the cheap path. XMP fills the gaps when the PDF
    // was generated by tools (LaTeX, Pandoc, mdBook) that skip Info.
    const title = strOrUndef(info.Title) ?? xmpString(xmp, "dc:title");
    const rawAuthor = strOrUndef(info.Author) ?? xmpString(xmp, "dc:creator");
    const authors = splitAuthors(rawAuthor);

    const language =
      strOrUndef(info.Language) ?? xmpString(xmp, "dc:language");
    const publisher =
      strOrUndef(info.Producer) ??
      strOrUndef(info.Creator) ??
      xmpString(xmp, "dc:publisher");

    const dateStr =
      strOrUndef(info.CreationDate) ?? xmpString(xmp, "xmp:CreateDate");
    const publishedAt = dateStr
      ? parsePdfDate(dateStr) ?? parseXmpDate(dateStr)
      : undefined;

    // Hand the cover renderer its own copy of the bytes (Buffer.from copies),
    // since pdfjs above may have neutered `data`/`buffer`.
    const cover = await renderFirstPageCover(Buffer.from(buffer));

    return {
      title,
      authors,
      language,
      publisher,
      publishedAt,
      pageCount: doc.numPages,
      cover,
    };
  } finally {
    // Tear down through the loading task rather than the document: pdfjs 6
    // dropped destroy() from the document proxy, and the task owns the
    // worker the document is only a view onto.
    await loadingTask.destroy();
  }
}

// pdfjs-dist v5 needs DOM globals Node lacks. Register them once from
// @napi-rs/canvas before any getDocument call. Idempotent.
let pdfGlobalsReady = false;
async function ensurePdfGlobals(): Promise<void> {
  if (pdfGlobalsReady) return;
  const canvas = await import("@napi-rs/canvas");
  const g = globalThis as unknown as Record<string, unknown>;
  g.DOMMatrix ??= canvas.DOMMatrix;
  g.ImageData ??= canvas.ImageData;
  g.Path2D ??= canvas.Path2D;
  pdfGlobalsReady = true;
}

function splitAuthors(raw: string | undefined): string[] {
  if (!raw) return [];
  return raw
    .split(/[,;]| and /i)
    .map((s) => s.trim())
    .filter(Boolean);
}

interface XmpLike {
  get(name: string): unknown;
}

function xmpString(xmp: XmpLike | null, key: string): string | undefined {
  if (!xmp) return undefined;
  const v = xmp.get(key);
  if (typeof v === "string") {
    const t = v.trim();
    return t || undefined;
  }
  // Some XMP fields parse as arrays (rdf:Seq / rdf:Bag — e.g. multi-author
  // dc:creator). Join them so downstream splitAuthors() can fan back out.
  if (Array.isArray(v)) {
    const joined = v
      .map((x) => (typeof x === "string" ? x.trim() : ""))
      .filter(Boolean)
      .join(", ");
    return joined || undefined;
  }
  return undefined;
}

function parseXmpDate(s: string): Date | undefined {
  // XMP dates are ISO-8601 (e.g. "2024-08-12T14:32:00Z"). Date's parser
  // already handles these; bail if it doesn't.
  const d = new Date(s);
  return isNaN(d.getTime()) ? undefined : d;
}

// Render page 1 to a PNG buffer via pdf-to-img — purpose-built lib that
// handles the pdfjs + canvas + font-loading wiring internally, which
// fights you in Node otherwise. Takes the already-read bytes (pdf-to-img
// accepts a Buffer/Uint8Array directly, confirmed via its types) so the file
// is never re-opened. Returns undefined on any failure so the scanner falls
// back to the format placeholder.
async function renderFirstPageCover(
  bytes: Buffer | Uint8Array,
): Promise<{ buffer: Buffer; ext: string } | undefined> {
  try {
    const { pdf } = await import("pdf-to-img");
    // scale 1 ≈ 72dpi; bump to 2 for sharper grid thumbnails.
    const document = await pdf(bytes, { scale: 2 });
    const buffer = await document.getPage(1);
    return { buffer, ext: "png" };
  } catch (err) {
    // Some PDFs trip pdf-to-img / pdfjs on encrypted streams or
    // unusual fonts. Falling back to the format placeholder is fine —
    // the title/author are still useful chrome.
    console.warn("[scanner] PDF cover render failed:", (err as Error).message);
    return undefined;
  }
}

function strOrUndef(v: unknown): string | undefined {
  if (typeof v !== "string") return undefined;
  const t = v.trim();
  return t || undefined;
}

// PDF dates look like:  D:YYYYMMDDHHmmSSOHH'mm'   (or simpler suffixes).
// We accept the common prefixes and ignore the timezone offset detail —
// good enough for "year published" display.
function parsePdfDate(s: string): Date | undefined {
  const m = /^D:(\d{4})(\d{2})?(\d{2})?(\d{2})?(\d{2})?(\d{2})?/.exec(s);
  if (!m) return undefined;
  const [, y, mo = "01", d = "01", h = "00", mi = "00", se = "00"] = m;
  const date = new Date(
    Date.UTC(
      parseInt(y, 10),
      parseInt(mo, 10) - 1,
      parseInt(d, 10),
      parseInt(h, 10),
      parseInt(mi, 10),
      parseInt(se, 10),
    ),
  );
  return isNaN(date.getTime()) ? undefined : date;
}
